### ISSUE TITLE
Header.js

### ISSUE THREAD

**Issue by Thirumalai08** [8020Coding/netflix-clone-frontend#1]
it showing error as module not found in import Icon from 'react-icons-kit' . Please kindly check the issue without fail

**Comment by Preet538-neitzen** [comment]
Its not an error with the repo per say.. You need to install and save react-icons-kit . Here : 
  https://www.npmjs.com/package/react-icons-kit

**Comment by subha1007** [comment]
hello sir can I talk to you

**Comment by Preet538-neitzen** [comment]
Yes sure.

**Comment by subha1007** [comment]
How talk to u?

**Comment by Preet538-neitzen** [comment]
Over here on Gmail itself.
